FROM docker.io/library/golang:1.25-alpine AS builder

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o /frg-devnet ./cmd/frg-devnet

FROM docker.io/library/alpine:latest
COPY --from=builder /frg-devnet /usr/local/bin/frg-devnet
WORKDIR /workspace
ENTRYPOINT ["frg-devnet"]
