// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proto/frg.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RawBytes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawBytes) Reset() {
	*x = RawBytes{}
	mi := &file_proto_frg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawBytes) ProtoMessage() {}

func (x *RawBytes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawBytes.ProtoReflect.Descriptor instead.
func (*RawBytes) Descriptor() ([]byte, []int) {
	return file_proto_frg_proto_rawDescGZIP(), []int{0}
}

func (x *RawBytes) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RawBytesArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          [][]byte               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawBytesArray) Reset() {
	*x = RawBytesArray{}
	mi := &file_proto_frg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawBytesArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawBytesArray) ProtoMessage() {}

func (x *RawBytesArray) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawBytesArray.ProtoReflect.Descriptor instead.
func (*RawBytesArray) Descriptor() ([]byte, []int) {
	return file_proto_frg_proto_rawDescGZIP(), []int{1}
}

func (x *RawBytesArray) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_proto_frg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_proto_frg_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SubmitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_frg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_frg_proto_rawDescGZIP(), []int{3}
}

type StatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Height         uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	StateRoot      []byte                 `protobuf:"bytes,2,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	PeerCount      uint64                 `protobuf:"varint,3,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	MempoolLen     uint64                 `protobuf:"varint,4,opt,name=mempool_len,json=mempoolLen,proto3" json:"mempool_len,omitempty"`
	ValidatorCount uint64                 `protobuf:"varint,5,opt,name=validator_count,json=validatorCount,proto3" json:"validator_count,omitempty"`
	ConsensusRound uint32                 `protobuf:"varint,6,opt,name=consensus_round,json=consensusRound,proto3" json:"consensus_round,omitempty"`
	ConsensusPhase string                 `protobuf:"bytes,7,opt,name=consensus_phase,json=consensusPhase,proto3" json:"consensus_phase,omitempty"`
	GrpcOnly       bool                   `protobuf:"varint,8,opt,name=grpc_only,json=grpcOnly,proto3" json:"grpc_only,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_frg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_frg_proto_rawDescGZIP(), []int{4}
}

func (x *StatusResponse) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *StatusResponse) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *StatusResponse) GetPeerCount() uint64 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

func (x *StatusResponse) GetMempoolLen() uint64 {
	if x != nil {
		return x.MempoolLen
	}
	return 0
}

func (x *StatusResponse) GetValidatorCount() uint64 {
	if x != nil {
		return x.ValidatorCount
	}
	return 0
}

func (x *StatusResponse) GetConsensusRound() uint32 {
	if x != nil {
		return x.ConsensusRound
	}
	return 0
}

func (x *StatusResponse) GetConsensusPhase() string {
	if x != nil {
		return x.ConsensusPhase
	}
	return ""
}

func (x *StatusResponse) GetGrpcOnly() bool {
	if x != nil {
		return x.GrpcOnly
	}
	return false
}

type AccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        []byte                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountRequest) Reset() {
	*x = AccountRequest{}
	mi := &file_proto_frg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRequest) ProtoMessage() {}

func (x *AccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRequest.ProtoReflect.Descriptor instead.
func (*AccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_frg_proto_rawDescGZIP(), []int{5}
}

func (x *AccountRequest) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

type AccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        []byte                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Balance       string                 `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Nonce         uint64                 `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountResponse) Reset() {
	*x = AccountResponse{}
	mi := &file_proto_frg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountResponse) ProtoMessage() {}

func (x *AccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountResponse.ProtoReflect.Descriptor instead.
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_frg_proto_rawDescGZIP(), []int{6}
}

func (x *AccountResponse) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *AccountResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *AccountResponse) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type ContractStateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress []byte                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	Key             []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContractStateRequest) Reset() {
	*x = ContractStateRequest{}
	mi := &file_proto_frg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractStateRequest) ProtoMessage() {}

func (x *ContractStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractStateRequest.ProtoReflect.Descriptor instead.
func (*ContractStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_frg_proto_rawDescGZIP(), []int{7}
}

func (x *ContractStateRequest) GetContractAddress() []byte {
	if x != nil {
		return x.ContractAddress
	}
	return nil
}

func (x *ContractStateRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type ContractStateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress []byte                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	Exists          bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	StateRoot       []byte                 `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	Key             []byte                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Found           bool                   `protobuf:"varint,5,opt,name=found,proto3" json:"found,omitempty"`
	Value           []byte                 `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContractStateResponse) Reset() {
	*x = ContractStateResponse{}
	mi := &file_proto_frg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractStateResponse) ProtoMessage() {}

func (x *ContractStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractStateResponse.ProtoReflect.Descriptor instead.
func (*ContractStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_frg_proto_rawDescGZIP(), []int{8}
}

func (x *ContractStateResponse) GetContractAddress() []byte {
	if x != nil {
		return x.ContractAddress
	}
	return nil
}

func (x *ContractStateResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *ContractStateResponse) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *ContractStateResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ContractStateResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ContractStateResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ValidatorEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        []byte                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Bond          string                 `protobuf:"bytes,2,opt,name=bond,proto3" json:"bond,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatorEntry) Reset() {
	*x = ValidatorEntry{}
	mi := &file_proto_frg_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorEntry) ProtoMessage() {}

func (x *ValidatorEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frg_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorEntry.ProtoReflect.Descriptor instead.
func (*ValidatorEntry) Descriptor() ([]byte, []int) {
	return file_proto_frg_proto_rawDescGZIP(), []int{9}
}

func (x *ValidatorEntry) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *ValidatorEntry) GetBond() string {
	if x != nil {
		return x.Bond
	}
	return ""
}

type ValidatorList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Validators    []*ValidatorEntry      `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatorList) Reset() {
	*x = ValidatorList{}
	mi := &file_proto_frg_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorList) ProtoMessage() {}

func (x *ValidatorList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frg_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorList.ProtoReflect.Descriptor instead.
func (*ValidatorList) Descriptor() ([]byte, []int) {
	return file_proto_frg_proto_rawDescGZIP(), []int{10}
}

func (x *ValidatorList) GetValidators() []*ValidatorEntry {
	if x != nil {
		return x.Validators
	}
	return nil
}

type MempoolEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txid          []byte                 `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Sender        string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Nonce         uint64                 `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MempoolEntry) Reset() {
	*x = MempoolEntry{}
	mi := &file_proto_frg_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MempoolEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MempoolEntry) ProtoMessage() {}

func (x *MempoolEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frg_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MempoolEntry.ProtoReflect.Descriptor instead.
func (*MempoolEntry) Descriptor() ([]byte, []int) {
	return file_proto_frg_proto_rawDescGZIP(), []int{11}
}

func (x *MempoolEntry) GetTxid() []byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *MempoolEntry) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MempoolEntry) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type MempoolList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*MempoolEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MempoolList) Reset() {
	*x = MempoolList{}
	mi := &file_proto_frg_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MempoolList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MempoolList) ProtoMessage() {}

func (x *MempoolList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frg_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MempoolList.ProtoReflect.Descriptor instead.
func (*MempoolList) Descriptor() ([]byte, []int) {
	return file_proto_frg_proto_rawDescGZIP(), []int{12}
}

func (x *MempoolList) GetEntries() []*MempoolEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type BlockTelemetryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Height zero means the latest committed block.
	Height        uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockTelemetryRequest) Reset() {
	*x = BlockTelemetryRequest{}
	mi := &file_proto_frg_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockTelemetryRequest) ProtoMessage() {}

func (x *BlockTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frg_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockTelemetryRequest.ProtoReflect.Descriptor instead.
func (*BlockTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_proto_frg_proto_rawDescGZIP(), []int{13}
}

func (x *BlockTelemetryRequest) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type TxTypeCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Count         uint64                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxTypeCount) Reset() {
	*x = TxTypeCount{}
	mi := &file_proto_frg_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxTypeCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxTypeCount) ProtoMessage() {}

func (x *TxTypeCount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frg_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxTypeCount.ProtoReflect.Descriptor instead.
func (*TxTypeCount) Descriptor() ([]byte, []int) {
	return file_proto_frg_proto_rawDescGZIP(), []int{14}
}

func (x *TxTypeCount) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *TxTypeCount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TxTypeCount) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SignatureCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     uint32                 `protobuf:"varint,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Count         uint64                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignatureCount) Reset() {
	*x = SignatureCount{}
	mi := &file_proto_frg_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureCount) ProtoMessage() {}

func (x *SignatureCount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frg_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureCount.ProtoReflect.Descriptor instead.
func (*SignatureCount) Descriptor() ([]byte, []int) {
	return file_proto_frg_proto_rawDescGZIP(), []int{15}
}

func (x *SignatureCount) GetSignature() uint32 {
	if x != nil {
		return x.Signature
	}
	return 0
}

func (x *SignatureCount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignatureCount) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RGLevelTelemetry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Level             uint32                 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Scale             uint32                 `protobuf:"varint,2,opt,name=scale,proto3" json:"scale,omitempty"`
	NodeCount         uint64                 `protobuf:"varint,3,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	SignatureCounts   []*SignatureCount      `protobuf:"bytes,4,rep,name=signature_counts,json=signatureCounts,proto3" json:"signature_counts,omitempty"`
	ContractDensity   float64                `protobuf:"fixed64,5,opt,name=contract_density,json=contractDensity,proto3" json:"contract_density,omitempty"`
	VolatileRegions   []uint64               `protobuf:"varint,6,rep,packed,name=volatile_regions,json=volatileRegions,proto3" json:"volatile_regions,omitempty"`
	StagnantRegions   []uint64               `protobuf:"varint,7,rep,packed,name=stagnant_regions,json=stagnantRegions,proto3" json:"stagnant_regions,omitempty"`
	TotalVolume       string                 `protobuf:"bytes,8,opt,name=total_volume,json=totalVolume,proto3" json:"total_volume,omitempty"`
	Variance          string                 `protobuf:"bytes,9,opt,name=variance,proto3" json:"variance,omitempty"`
	ContractTxCount   uint64                 `protobuf:"varint,10,opt,name=contract_tx_count,json=contractTxCount,proto3" json:"contract_tx_count,omitempty"`
	ContractNodeCount uint64                 `protobuf:"varint,11,opt,name=contract_node_count,json=contractNodeCount,proto3" json:"contract_node_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RGLevelTelemetry) Reset() {
	*x = RGLevelTelemetry{}
	mi := &file_proto_frg_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RGLevelTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RGLevelTelemetry) ProtoMessage() {}

func (x *RGLevelTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frg_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RGLevelTelemetry.ProtoReflect.Descriptor instead.
func (*RGLevelTelemetry) Descriptor() ([]byte, []int) {
	return file_proto_frg_proto_rawDescGZIP(), []int{16}
}

func (x *RGLevelTelemetry) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *RGLevelTelemetry) GetScale() uint32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *RGLevelTelemetry) GetNodeCount() uint64 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *RGLevelTelemetry) GetSignatureCounts() []*SignatureCount {
	if x != nil {
		return x.SignatureCounts
	}
	return nil
}

func (x *RGLevelTelemetry) GetContractDensity() float64 {
	if x != nil {
		return x.ContractDensity
	}
	return 0
}

func (x *RGLevelTelemetry) GetVolatileRegions() []uint64 {
	if x != nil {
		return x.VolatileRegions
	}
	return nil
}

func (x *RGLevelTelemetry) GetStagnantRegions() []uint64 {
	if x != nil {
		return x.StagnantRegions
	}
	return nil
}

func (x *RGLevelTelemetry) GetTotalVolume() string {
	if x != nil {
		return x.TotalVolume
	}
	return ""
}

func (x *RGLevelTelemetry) GetVariance() string {
	if x != nil {
		return x.Variance
	}
	return ""
}

func (x *RGLevelTelemetry) GetContractTxCount() uint64 {
	if x != nil {
		return x.ContractTxCount
	}
	return 0
}

func (x *RGLevelTelemetry) GetContractNodeCount() uint64 {
	if x != nil {
		return x.ContractNodeCount
	}
	return 0
}

type BlockTelemetryResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Height                uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	StateRoot             []byte                 `protobuf:"bytes,2,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	ProposerPubkey        []byte                 `protobuf:"bytes,3,opt,name=proposer_pubkey,json=proposerPubkey,proto3" json:"proposer_pubkey,omitempty"`
	TxCount               uint64                 `protobuf:"varint,4,opt,name=tx_count,json=txCount,proto3" json:"tx_count,omitempty"`
	TotalValue            string                 `protobuf:"bytes,5,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	MeanValue             string                 `protobuf:"bytes,6,opt,name=mean_value,json=meanValue,proto3" json:"mean_value,omitempty"`
	Variance              string                 `protobuf:"bytes,7,opt,name=variance,proto3" json:"variance,omitempty"`
	TxTypes               []*TxTypeCount         `protobuf:"bytes,8,rep,name=tx_types,json=txTypes,proto3" json:"tx_types,omitempty"`
	Levels                []*RGLevelTelemetry    `protobuf:"bytes,9,rep,name=levels,proto3" json:"levels,omitempty"`
	ContractStateIncluded bool                   `protobuf:"varint,10,opt,name=contract_state_included,json=contractStateIncluded,proto3" json:"contract_state_included,omitempty"`
	Warning               string                 `protobuf:"bytes,11,opt,name=warning,proto3" json:"warning,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BlockTelemetryResponse) Reset() {
	*x = BlockTelemetryResponse{}
	mi := &file_proto_frg_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockTelemetryResponse) ProtoMessage() {}

func (x *BlockTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frg_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockTelemetryResponse.ProtoReflect.Descriptor instead.
func (*BlockTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_proto_frg_proto_rawDescGZIP(), []int{17}
}

func (x *BlockTelemetryResponse) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockTelemetryResponse) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *BlockTelemetryResponse) GetProposerPubkey() []byte {
	if x != nil {
		return x.ProposerPubkey
	}
	return nil
}

func (x *BlockTelemetryResponse) GetTxCount() uint64 {
	if x != nil {
		return x.TxCount
	}
	return 0
}

func (x *BlockTelemetryResponse) GetTotalValue() string {
	if x != nil {
		return x.TotalValue
	}
	return ""
}

func (x *BlockTelemetryResponse) GetMeanValue() string {
	if x != nil {
		return x.MeanValue
	}
	return ""
}

func (x *BlockTelemetryResponse) GetVariance() string {
	if x != nil {
		return x.Variance
	}
	return ""
}

func (x *BlockTelemetryResponse) GetTxTypes() []*TxTypeCount {
	if x != nil {
		return x.TxTypes
	}
	return nil
}

func (x *BlockTelemetryResponse) GetLevels() []*RGLevelTelemetry {
	if x != nil {
		return x.Levels
	}
	return nil
}

func (x *BlockTelemetryResponse) GetContractStateIncluded() bool {
	if x != nil {
		return x.ContractStateIncluded
	}
	return false
}

func (x *BlockTelemetryResponse) GetWarning() string {
	if x != nil {
		return x.Warning
	}
	return ""
}

var File_proto_frg_proto protoreflect.FileDescriptor

const file_proto_frg_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/frg.proto\x12\x03frg\"\x1e\n" +
	"\bRawBytes\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"#\n" +
	"\rRawBytesArray\x12\x12\n" +
	"\x04data\x18\x01 \x03(\fR\x04data\"6\n" +
	"\x0eSubmitResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\a\n" +
	"\x05Empty\"\x9f\x02\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x1d\n" +
	"\n" +
	"state_root\x18\x02 \x01(\fR\tstateRoot\x12\x1d\n" +
	"\n" +
	"peer_count\x18\x03 \x01(\x04R\tpeerCount\x12\x1f\n" +
	"\vmempool_len\x18\x04 \x01(\x04R\n" +
	"mempoolLen\x12'\n" +
	"\x0fvalidator_count\x18\x05 \x01(\x04R\x0evalidatorCount\x12'\n" +
	"\x0fconsensus_round\x18\x06 \x01(\rR\x0econsensusRound\x12'\n" +
	"\x0fconsensus_phase\x18\a \x01(\tR\x0econsensusPhase\x12\x1b\n" +
	"\tgrpc_only\x18\b \x01(\bR\bgrpcOnly\"(\n" +
	"\x0eAccountRequest\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\"Y\n" +
	"\x0fAccountResponse\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\x12\x18\n" +
	"\abalance\x18\x02 \x01(\tR\abalance\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\x04R\x05nonce\"S\n" +
	"\x14ContractStateRequest\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\fR\x0fcontractAddress\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"\xb7\x01\n" +
	"\x15ContractStateResponse\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\fR\x0fcontractAddress\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\x12\x1d\n" +
	"\n" +
	"state_root\x18\x03 \x01(\fR\tstateRoot\x12\x10\n" +
	"\x03key\x18\x04 \x01(\fR\x03key\x12\x14\n" +
	"\x05found\x18\x05 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x06 \x01(\fR\x05value\"<\n" +
	"\x0eValidatorEntry\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\x12\x12\n" +
	"\x04bond\x18\x02 \x01(\tR\x04bond\"D\n" +
	"\rValidatorList\x123\n" +
	"\n" +
	"validators\x18\x01 \x03(\v2\x13.frg.ValidatorEntryR\n" +
	"validators\"P\n" +
	"\fMempoolEntry\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\fR\x04txid\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\x04R\x05nonce\":\n" +
	"\vMempoolList\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.frg.MempoolEntryR\aentries\"/\n" +
	"\x15BlockTelemetryRequest\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\"K\n" +
	"\vTxTypeCount\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x04R\x05count\"X\n" +
	"\x0eSignatureCount\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\rR\tsignature\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x04R\x05count\"\xb9\x03\n" +
	"\x10RGLevelTelemetry\x12\x14\n" +
	"\x05level\x18\x01 \x01(\rR\x05level\x12\x14\n" +
	"\x05scale\x18\x02 \x01(\rR\x05scale\x12\x1d\n" +
	"\n" +
	"node_count\x18\x03 \x01(\x04R\tnodeCount\x12>\n" +
	"\x10signature_counts\x18\x04 \x03(\v2\x13.frg.SignatureCountR\x0fsignatureCounts\x12)\n" +
	"\x10contract_density\x18\x05 \x01(\x01R\x0fcontractDensity\x12)\n" +
	"\x10volatile_regions\x18\x06 \x03(\x04R\x0fvolatileRegions\x12)\n" +
	"\x10stagnant_regions\x18\a \x03(\x04R\x0fstagnantRegions\x12!\n" +
	"\ftotal_volume\x18\b \x01(\tR\vtotalVolume\x12\x1a\n" +
	"\bvariance\x18\t \x01(\tR\bvariance\x12*\n" +
	"\x11contract_tx_count\x18\n" +
	" \x01(\x04R\x0fcontractTxCount\x12.\n" +
	"\x13contract_node_count\x18\v \x01(\x04R\x11contractNodeCount\"\x9d\x03\n" +
	"\x16BlockTelemetryResponse\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x1d\n" +
	"\n" +
	"state_root\x18\x02 \x01(\fR\tstateRoot\x12'\n" +
	"\x0fproposer_pubkey\x18\x03 \x01(\fR\x0eproposerPubkey\x12\x19\n" +
	"\btx_count\x18\x04 \x01(\x04R\atxCount\x12\x1f\n" +
	"\vtotal_value\x18\x05 \x01(\tR\n" +
	"totalValue\x12\x1d\n" +
	"\n" +
	"mean_value\x18\x06 \x01(\tR\tmeanValue\x12\x1a\n" +
	"\bvariance\x18\a \x01(\tR\bvariance\x12+\n" +
	"\btx_types\x18\b \x03(\v2\x10.frg.TxTypeCountR\atxTypes\x12-\n" +
	"\x06levels\x18\t \x03(\v2\x15.frg.RGLevelTelemetryR\x06levels\x126\n" +
	"\x17contract_state_included\x18\n" +
	" \x01(\bR\x15contractStateIncluded\x12\x18\n" +
	"\awarning\x18\v \x01(\tR\awarning2\xfc\x03\n" +
	"\x03FRG\x12.\n" +
	"\bSubmitTx\x12\r.frg.RawBytes\x1a\x13.frg.SubmitResponse\x126\n" +
	"\vSubmitBatch\x12\x12.frg.RawBytesArray\x1a\x13.frg.SubmitResponse\x12.\n" +
	"\x0fSubscribeBlocks\x12\n" +
	".frg.Empty\x1a\r.frg.RawBytes0\x01\x12,\n" +
	"\tGetStatus\x12\n" +
	".frg.Empty\x1a\x13.frg.StatusResponse\x127\n" +
	"\n" +
	"GetAccount\x12\x13.frg.AccountRequest\x1a\x14.frg.AccountResponse\x12I\n" +
	"\x10GetContractState\x12\x19.frg.ContractStateRequest\x1a\x1a.frg.ContractStateResponse\x120\n" +
	"\x0eListValidators\x12\n" +
	".frg.Empty\x1a\x12.frg.ValidatorList\x12+\n" +
	"\vListMempool\x12\n" +
	".frg.Empty\x1a\x10.frg.MempoolList\x12L\n" +
	"\x11GetBlockTelemetry\x12\x1a.frg.BlockTelemetryRequest\x1a\x1b.frg.BlockTelemetryResponseB\x1eZ\x1cgithub.com/imattau/frg/protob\x06proto3"

var (
	file_proto_frg_proto_rawDescOnce sync.Once
	file_proto_frg_proto_rawDescData []byte
)

func file_proto_frg_proto_rawDescGZIP() []byte {
	file_proto_frg_proto_rawDescOnce.Do(func() {
		file_proto_frg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_frg_proto_rawDesc), len(file_proto_frg_proto_rawDesc)))
	})
	return file_proto_frg_proto_rawDescData
}

var file_proto_frg_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_frg_proto_goTypes = []any{
	(*RawBytes)(nil),               // 0: frg.RawBytes
	(*RawBytesArray)(nil),          // 1: frg.RawBytesArray
	(*SubmitResponse)(nil),         // 2: frg.SubmitResponse
	(*Empty)(nil),                  // 3: frg.Empty
	(*StatusResponse)(nil),         // 4: frg.StatusResponse
	(*AccountRequest)(nil),         // 5: frg.AccountRequest
	(*AccountResponse)(nil),        // 6: frg.AccountResponse
	(*ContractStateRequest)(nil),   // 7: frg.ContractStateRequest
	(*ContractStateResponse)(nil),  // 8: frg.ContractStateResponse
	(*ValidatorEntry)(nil),         // 9: frg.ValidatorEntry
	(*ValidatorList)(nil),          // 10: frg.ValidatorList
	(*MempoolEntry)(nil),           // 11: frg.MempoolEntry
	(*MempoolList)(nil),            // 12: frg.MempoolList
	(*BlockTelemetryRequest)(nil),  // 13: frg.BlockTelemetryRequest
	(*TxTypeCount)(nil),            // 14: frg.TxTypeCount
	(*SignatureCount)(nil),         // 15: frg.SignatureCount
	(*RGLevelTelemetry)(nil),       // 16: frg.RGLevelTelemetry
	(*BlockTelemetryResponse)(nil), // 17: frg.BlockTelemetryResponse
}
var file_proto_frg_proto_depIdxs = []int32{
	9,  // 0: frg.ValidatorList.validators:type_name -> frg.ValidatorEntry
	11, // 1: frg.MempoolList.entries:type_name -> frg.MempoolEntry
	15, // 2: frg.RGLevelTelemetry.signature_counts:type_name -> frg.SignatureCount
	14, // 3: frg.BlockTelemetryResponse.tx_types:type_name -> frg.TxTypeCount
	16, // 4: frg.BlockTelemetryResponse.levels:type_name -> frg.RGLevelTelemetry
	0,  // 5: frg.FRG.SubmitTx:input_type -> frg.RawBytes
	1,  // 6: frg.FRG.SubmitBatch:input_type -> frg.RawBytesArray
	3,  // 7: frg.FRG.SubscribeBlocks:input_type -> frg.Empty
	3,  // 8: frg.FRG.GetStatus:input_type -> frg.Empty
	5,  // 9: frg.FRG.GetAccount:input_type -> frg.AccountRequest
	7,  // 10: frg.FRG.GetContractState:input_type -> frg.ContractStateRequest
	3,  // 11: frg.FRG.ListValidators:input_type -> frg.Empty
	3,  // 12: frg.FRG.ListMempool:input_type -> frg.Empty
	13, // 13: frg.FRG.GetBlockTelemetry:input_type -> frg.BlockTelemetryRequest
	2,  // 14: frg.FRG.SubmitTx:output_type -> frg.SubmitResponse
	2,  // 15: frg.FRG.SubmitBatch:output_type -> frg.SubmitResponse
	0,  // 16: frg.FRG.SubscribeBlocks:output_type -> frg.RawBytes
	4,  // 17: frg.FRG.GetStatus:output_type -> frg.StatusResponse
	6,  // 18: frg.FRG.GetAccount:output_type -> frg.AccountResponse
	8,  // 19: frg.FRG.GetContractState:output_type -> frg.ContractStateResponse
	10, // 20: frg.FRG.ListValidators:output_type -> frg.ValidatorList
	12, // 21: frg.FRG.ListMempool:output_type -> frg.MempoolList
	17, // 22: frg.FRG.GetBlockTelemetry:output_type -> frg.BlockTelemetryResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_frg_proto_init() }
func file_proto_frg_proto_init() {
	if File_proto_frg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_frg_proto_rawDesc), len(file_proto_frg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_frg_proto_goTypes,
		DependencyIndexes: file_proto_frg_proto_depIdxs,
		MessageInfos:      file_proto_frg_proto_msgTypes,
	}.Build()
	File_proto_frg_proto = out.File
	file_proto_frg_proto_goTypes = nil
	file_proto_frg_proto_depIdxs = nil
}
