// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/frg.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FRG_SubmitTx_FullMethodName          = "/frg.FRG/SubmitTx"
	FRG_SubmitBatch_FullMethodName       = "/frg.FRG/SubmitBatch"
	FRG_SubscribeBlocks_FullMethodName   = "/frg.FRG/SubscribeBlocks"
	FRG_GetStatus_FullMethodName         = "/frg.FRG/GetStatus"
	FRG_GetAccount_FullMethodName        = "/frg.FRG/GetAccount"
	FRG_GetContractState_FullMethodName  = "/frg.FRG/GetContractState"
	FRG_ListValidators_FullMethodName    = "/frg.FRG/ListValidators"
	FRG_ListMempool_FullMethodName       = "/frg.FRG/ListMempool"
	FRG_GetBlockTelemetry_FullMethodName = "/frg.FRG/GetBlockTelemetry"
)

// FRGClient is the client API for FRG service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FRGClient interface {
	// SubmitTx accepts FRG's Go-side serialized, signed transaction bytes.
	// The transaction wire format and signing preimage are intentionally not
	// defined in this proto; clients that need to construct signed transactions
	// must use FRG wallet/Go-side transaction code until that format is specified.
	SubmitTx(ctx context.Context, in *RawBytes, opts ...grpc.CallOption) (*SubmitResponse, error)
	// SubmitBatch accepts a batch of the same opaque signed transaction bytes.
	SubmitBatch(ctx context.Context, in *RawBytesArray, opts ...grpc.CallOption) (*SubmitResponse, error)
	SubscribeBlocks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RawBytes], error)
	GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	GetAccount(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountResponse, error)
	GetContractState(ctx context.Context, in *ContractStateRequest, opts ...grpc.CallOption) (*ContractStateResponse, error)
	ListValidators(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ValidatorList, error)
	ListMempool(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MempoolList, error)
	GetBlockTelemetry(ctx context.Context, in *BlockTelemetryRequest, opts ...grpc.CallOption) (*BlockTelemetryResponse, error)
}

type fRGClient struct {
	cc grpc.ClientConnInterface
}

func NewFRGClient(cc grpc.ClientConnInterface) FRGClient {
	return &fRGClient{cc}
}

func (c *fRGClient) SubmitTx(ctx context.Context, in *RawBytes, opts ...grpc.CallOption) (*SubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, FRG_SubmitTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fRGClient) SubmitBatch(ctx context.Context, in *RawBytesArray, opts ...grpc.CallOption) (*SubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, FRG_SubmitBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fRGClient) SubscribeBlocks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RawBytes], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FRG_ServiceDesc.Streams[0], FRG_SubscribeBlocks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, RawBytes]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FRG_SubscribeBlocksClient = grpc.ServerStreamingClient[RawBytes]

func (c *fRGClient) GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, FRG_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fRGClient) GetAccount(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountResponse)
	err := c.cc.Invoke(ctx, FRG_GetAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fRGClient) GetContractState(ctx context.Context, in *ContractStateRequest, opts ...grpc.CallOption) (*ContractStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContractStateResponse)
	err := c.cc.Invoke(ctx, FRG_GetContractState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fRGClient) ListValidators(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ValidatorList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidatorList)
	err := c.cc.Invoke(ctx, FRG_ListValidators_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fRGClient) ListMempool(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MempoolList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MempoolList)
	err := c.cc.Invoke(ctx, FRG_ListMempool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fRGClient) GetBlockTelemetry(ctx context.Context, in *BlockTelemetryRequest, opts ...grpc.CallOption) (*BlockTelemetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockTelemetryResponse)
	err := c.cc.Invoke(ctx, FRG_GetBlockTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FRGServer is the server API for FRG service.
// All implementations must embed UnimplementedFRGServer
// for forward compatibility.
type FRGServer interface {
	// SubmitTx accepts FRG's Go-side serialized, signed transaction bytes.
	// The transaction wire format and signing preimage are intentionally not
	// defined in this proto; clients that need to construct signed transactions
	// must use FRG wallet/Go-side transaction code until that format is specified.
	SubmitTx(context.Context, *RawBytes) (*SubmitResponse, error)
	// SubmitBatch accepts a batch of the same opaque signed transaction bytes.
	SubmitBatch(context.Context, *RawBytesArray) (*SubmitResponse, error)
	SubscribeBlocks(*Empty, grpc.ServerStreamingServer[RawBytes]) error
	GetStatus(context.Context, *Empty) (*StatusResponse, error)
	GetAccount(context.Context, *AccountRequest) (*AccountResponse, error)
	GetContractState(context.Context, *ContractStateRequest) (*ContractStateResponse, error)
	ListValidators(context.Context, *Empty) (*ValidatorList, error)
	ListMempool(context.Context, *Empty) (*MempoolList, error)
	GetBlockTelemetry(context.Context, *BlockTelemetryRequest) (*BlockTelemetryResponse, error)
	mustEmbedUnimplementedFRGServer()
}

// UnimplementedFRGServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFRGServer struct{}

func (UnimplementedFRGServer) SubmitTx(context.Context, *RawBytes) (*SubmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTx not implemented")
}
func (UnimplementedFRGServer) SubmitBatch(context.Context, *RawBytesArray) (*SubmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitBatch not implemented")
}
func (UnimplementedFRGServer) SubscribeBlocks(*Empty, grpc.ServerStreamingServer[RawBytes]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeBlocks not implemented")
}
func (UnimplementedFRGServer) GetStatus(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedFRGServer) GetAccount(context.Context, *AccountRequest) (*AccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedFRGServer) GetContractState(context.Context, *ContractStateRequest) (*ContractStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContractState not implemented")
}
func (UnimplementedFRGServer) ListValidators(context.Context, *Empty) (*ValidatorList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListValidators not implemented")
}
func (UnimplementedFRGServer) ListMempool(context.Context, *Empty) (*MempoolList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMempool not implemented")
}
func (UnimplementedFRGServer) GetBlockTelemetry(context.Context, *BlockTelemetryRequest) (*BlockTelemetryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockTelemetry not implemented")
}
func (UnimplementedFRGServer) mustEmbedUnimplementedFRGServer() {}
func (UnimplementedFRGServer) testEmbeddedByValue()             {}

// UnsafeFRGServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FRGServer will
// result in compilation errors.
type UnsafeFRGServer interface {
	mustEmbedUnimplementedFRGServer()
}

func RegisterFRGServer(s grpc.ServiceRegistrar, srv FRGServer) {
	// If the following call pancis, it indicates UnimplementedFRGServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FRG_ServiceDesc, srv)
}

func _FRG_SubmitTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawBytes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FRGServer).SubmitTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FRG_SubmitTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FRGServer).SubmitTx(ctx, req.(*RawBytes))
	}
	return interceptor(ctx, in, info, handler)
}

func _FRG_SubmitBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawBytesArray)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FRGServer).SubmitBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FRG_SubmitBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FRGServer).SubmitBatch(ctx, req.(*RawBytesArray))
	}
	return interceptor(ctx, in, info, handler)
}

func _FRG_SubscribeBlocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FRGServer).SubscribeBlocks(m, &grpc.GenericServerStream[Empty, RawBytes]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FRG_SubscribeBlocksServer = grpc.ServerStreamingServer[RawBytes]

func _FRG_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FRGServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FRG_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FRGServer).GetStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FRG_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FRGServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FRG_GetAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FRGServer).GetAccount(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FRG_GetContractState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContractStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FRGServer).GetContractState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FRG_GetContractState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FRGServer).GetContractState(ctx, req.(*ContractStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FRG_ListValidators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FRGServer).ListValidators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FRG_ListValidators_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FRGServer).ListValidators(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FRG_ListMempool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FRGServer).ListMempool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FRG_ListMempool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FRGServer).ListMempool(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FRG_GetBlockTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockTelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FRGServer).GetBlockTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FRG_GetBlockTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FRGServer).GetBlockTelemetry(ctx, req.(*BlockTelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FRG_ServiceDesc is the grpc.ServiceDesc for FRG service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FRG_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "frg.FRG",
	HandlerType: (*FRGServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTx",
			Handler:    _FRG_SubmitTx_Handler,
		},
		{
			MethodName: "SubmitBatch",
			Handler:    _FRG_SubmitBatch_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _FRG_GetStatus_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _FRG_GetAccount_Handler,
		},
		{
			MethodName: "GetContractState",
			Handler:    _FRG_GetContractState_Handler,
		},
		{
			MethodName: "ListValidators",
			Handler:    _FRG_ListValidators_Handler,
		},
		{
			MethodName: "ListMempool",
			Handler:    _FRG_ListMempool_Handler,
		},
		{
			MethodName: "GetBlockTelemetry",
			Handler:    _FRG_GetBlockTelemetry_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeBlocks",
			Handler:       _FRG_SubscribeBlocks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/frg.proto",
}
